Backend/Interview.Domain/IRepository.cs
Backend/Interview.Infrastructure/Database/AppDbContext.cs
Backend/Interview.Infrastructure/Database/Configurations/EntityTypeConfigurationBase.cs
Backend/Interview.Infrastructure/Database/Configurations/UserTypeConfiguration.cs
Backend/Interview.Infrastructure/Database/EfRepository.cs
Backend/Interview.Infrastructure/Interview.Infrastructure.csproj

Added EF core

---

Backend/Interview.Backend/Controllers/Questions/QuestionController.cs
Backend/Interview.Backend/Controllers/Rooms/RoomController.cs
Backend/Interview.Backend/Controllers/Users/UserController.cs
Backend/Interview.Backend/Program.cs
Backend/Interview.Domain/Questions/IQuestionRepository.cs
Backend/Interview.Domain/Rooms/IRoomRepository.cs
Backend/Interview.Infrastructure/Questions/QuestionRepository.cs
Backend/Interview.Infrastructure/Rooms/RoomRepository.cs

- Add repository for Question/Room
- Add controller for Question/Room

feature/#7 Добавлены репозитории и контроллеры для Question и Room

---

Backend/Interview.Infrastructure/Chat/TokenProviders/ITwitchTokenProvider.cs
Backend/Interview.Infrastructure/Chat/TokenProviders/ReloadableCacheTwitchTokenProvider.cs
Backend/Interview.Infrastructure/Chat/TokenProviders/TwitchToken.cs
Backend/Interview.Infrastructure/Chat/TokenProviders/TwitchTokenProvider.cs

Добавил функционал получения токена для Twitch

Infrastructure, Twitch - Added TwitchToken

---

Backend/Interview.Domain/Rooms/Service/Records/Request/RoomCreateRequest.cs
Backend/Interview.Domain/Rooms/Service/RoomService.cs
Backend/Interview.Test/Integrations/RoomServiceTest.cs
Backend/Interview.Test/Units/Rooms/RoomServiceTest.cs

feature/#48 Добавлено в метод создания комнаты поиск и добавление пользователей

---

Backend/Interview.Backend/Questions/QuestionController.cs
Backend/Interview.Domain/Questions/QuestionService.cs
Backend/Interview.Domain/Questions/Records/Response/QuestionItem.cs
Backend/Interview.Test/Integrations/QuestionServiceTest.cs
Backend/Interview.Test/Units/Questions/QuestionServiceTest.cs

- Add method FindById for question

feature/#49 Добавлен метод поиска Question by id

---

Backend/Interview.Backend/RoomQuestions/RoomQuestionController.cs
Backend/Interview.Backend/RoomReactions/RoomReactionController.cs
Backend/Interview.DependencyInjection/ServiceCollectionExt.cs
Backend/Interview.Domain/Reactions/IReactionRepository.cs
Backend/Interview.Domain/Reactions/Reaction.cs
Backend/Interview.Domain/RoomQuestionReactions/IRoomQuestionReactionRepository.cs
Backend/Interview.Domain/RoomQuestionReactions/Records/Response/RoomQuestionReactionDetail.cs
Backend/Interview.Domain/RoomQuestionReactions/Records/RoomQuestionReactionCreateRequest.cs
Backend/Interview.Domain/RoomQuestionReactions/RoomQuestionReaction.cs
Backend/Interview.Domain/RoomQuestionReactions/RoomQuestionReactionService.cs
Backend/Interview.Domain/RoomQuestions/IRoomQuestionRepository.cs
Backend/Interview.Domain/RoomQuestions/Records/Response/RoomQuestionDetail.cs
Backend/Interview.Domain/RoomQuestions/Records/RoomQuestionChangeActiveRequest.cs
Backend/Interview.Domain/RoomQuestions/RoomQuestion.cs
Backend/Interview.Domain/RoomQuestions/RoomQuestionService.cs
Backend/Interview.Domain/RoomQuestions/RoomQuestionState.cs
Backend/Interview.Domain/Rooms/Room.cs
Backend/Interview.Domain/Rooms/Service/RoomService.cs
Backend/Interview.Infrastructure/Database/AppDbContext.cs
Backend/Interview.Infrastructure/Database/Configurations/ReactionConfiguration.cs
Backend/Interview.Infrastructure/Database/Configurations/RoomQuestionReactionTypeConfiguration.cs
Backend/Interview.Infrastructure/Database/Configurations/RoomQuestionTypeConfiguration.cs
Backend/Interview.Infrastructure/Database/Configurations/RoomTypeConfiguration.cs
Backend/Interview.Infrastructure/Reactions/ReactionRepository.cs
Backend/Interview.Infrastructure/RoomQuestionReactions/RoomQuestionReactionRepository.cs
Backend/Interview.Infrastructure/RoomQuestions/RoomQuestionRepository.cs
Backend/Interview.Infrastructure/Rooms/RoomRepository.cs

Feature/#59 

---

Backend/Interview.Domain/Rooms/Room.cs
Backend/Interview.Domain/Rooms/Service/Records/Request/RoomCreateRequest.cs
Backend/Interview.Domain/Rooms/Service/Records/Request/RoomPatchUpdateRequest.cs
Backend/Interview.Domain/Rooms/Service/RoomService.cs
Backend/Interview.Infrastructure/Database/Configurations/RoomTypeConfiguration.cs
Backend/Interview.Test/Integrations/RoomServiceTest.cs
Backend/Interview.Test/Units/Rooms/RoomRepositoryTest.cs

- Add twitch channel column in room
- Add in endpoint room/create
- Add in endpoint room/update

feature/#72 Add twitch channel column in room

---

Backend/Interview.Backend/Auth/ClaimsPrincipalExt.cs

feature/#62 Исправлена установка идентификатора пользователя в claim

---

Backend/Interview.Backend/RoomParticipants/RoomParticipantController.cs
Backend/Interview.Domain/Repository/IRepository.cs
Backend/Interview.Domain/RoomParticipants/IRoomParticipantRepository.cs
Backend/Interview.Domain/RoomParticipants/Records/Request/RoomParticipantChangeStatusRequest.cs
Backend/Interview.Domain/RoomParticipants/Records/Response/RoomParticipantDetail.cs
Backend/Interview.Domain/RoomParticipants/Service/RoomParticipantService.cs
Backend/Interview.Infrastructure/Database/EfRepository.cs
Backend/Interview.Infrastructure/RoomParticipants/RoomParticipantRepository.cs

- Add endpoint for change user status

feature/#66 Добавлена возможность изменять тип участника

---

Backend/Interview.Backend/Reactions/ReactionController.cs
Backend/Interview.DependencyInjection/ServiceCollectionExt.cs
Backend/Interview.Domain/Reactions/ReactionService.cs
Backend/Interview.Domain/Reactions/Records/ReactionDetail.cs

feature/#67 Добавлено получение страниц реакций 

---

Backend/Interview.Backend/RoomParticipants/RoomParticipantController.cs
Backend/Interview.Backend/RoomQuestions/RoomQuestionController.cs
Backend/Interview.Domain/RoomParticipants/Records/Request/RoomParticipantChangeStatusRequest.cs
Backend/Interview.Domain/RoomParticipants/Service/RoomParticipantService.cs
Backend/Interview.Domain/RoomQuestions/RoomQuestionService.cs

- Change type user type for create participant

feature/#81 Изменен тип пользователя для добавления участника комнаты

---

Backend/Interview.Backend/RoomParticipants/RoomParticipantController.cs
Backend/Interview.Backend/Rooms/RoomController.cs
Backend/Interview.Backend/ServiceConfigurator.cs
Backend/Interview.Domain/Connections/IConnectUserSource.cs
Backend/Interview.Domain/Repository/IMapper.cs
Backend/Interview.Domain/Repository/IRepository.cs
Backend/Interview.Domain/RoomParticipants/Records/Request/RoomParticipantChangeStatusRequest.cs
Backend/Interview.Domain/RoomParticipants/Records/Response/RoomParticipantDetail.cs
Backend/Interview.Domain/RoomParticipants/Service/RoomParticipantService.cs
Backend/Interview.Domain/RoomQuestionReactions/Mappers/ReactionTypeOnlyMapper.cs
Backend/Interview.Domain/RoomQuestionReactions/Specifications/RoomReactionsSpecification.cs
Backend/Interview.Domain/RoomQuestions/Records/Response/RoomQuestionDetail.cs
Backend/Interview.Domain/RoomQuestions/RoomQuestionService.cs
Backend/Interview.Domain/Rooms/IRoomRepository.cs
Backend/Interview.Domain/Rooms/Room.cs
Backend/Interview.Domain/Rooms/Service/Records/Response/Detail/RoomDetail.cs
Backend/Interview.Domain/Rooms/Service/Records/Response/Detail/RoomQuestionDetail.cs
Backend/Interview.Domain/Rooms/Service/Records/Response/Detail/RoomUserDetail.cs
Backend/Interview.Domain/Rooms/Service/Records/Response/RoomStates/RoomState.cs
Backend/Interview.Domain/Rooms/Service/Records/Response/RoomStates/RoomStateQuestion.cs
Backend/Interview.Domain/Rooms/Service/RoomService.cs
Backend/Interview.Infrastructure/Database/EfRepository.cs
Backend/Interview.Infrastructure/RoomQuestionReactions/RoomQuestionReactionRepository.cs
Backend/Interview.Infrastructure/Rooms/RoomRepository.cs
Backend/Interview.Test/Integrations/RoomServiceTest.cs
Backend/Interview.Test/Units/Rooms/RoomServiceTest.cs

Добавил метод GetRoomState в Room

Backend, RoomController - Added GetRoomState endpoint

---

Backend/Interview.Backend/Interview.Backend.csproj
Backend/Interview.Backend/MiddlewareConfigurator.cs
Backend/Interview.Backend/Program.cs
Backend/Interview.Backend/Questions/QuestionController.cs
Backend/Interview.Domain/Questions/QuestionEditRequest.cs
Backend/Interview.Domain/Questions/QuestionService.cs
Backend/Interview.Domain/Rooms/Analytics.cs
Backend/Interview.Infrastructure/Rooms/RoomRepository.cs

- Change architecture Rest for QuestionController

feature/#138 Стандартизировал REST API для Question

---

Backend/Interview.Backend/RoomQuestions/RoomQuestionController.cs
Backend/Interview.Backend/RoomReactions/RoomReactionController.cs
Backend/Interview.Domain/RoomQuestionReactions/RoomQuestionReactionService.cs
Backend/Interview.Domain/RoomQuestions/RoomQuestionService.cs

feature/#159 Рефакторинг контроллеров

---

Backend/Interview.Domain/Rooms/Service/Records/Response/Page/RoomPageDetail.cs
Backend/Interview.Infrastructure/Rooms/RoomRepository.cs

Статус комнаты (`'Active' | 'Close'`) в GET /rooms

Backend, RoomRepository - RoomStatus in GetDetailedPageAsync

---

Backend/Interview.Backend/RoomReviews/RoomReviewController.cs
Backend/Interview.Domain/RoomReviews/IRoomReviewRepository.cs
Backend/Interview.Domain/RoomReviews/Response/Page/RoomReviewPageDetail.cs
Backend/Interview.Domain/RoomReviews/RoomReviewService.cs
Backend/Interview.Infrastructure/RoomReviews/RoomReviewRepository.cs

Отображение ников пользователей в запросе страницы room-reviews

Backend, RoomReviewRepository - User nickname in GetDetailedPageAsync

---

Backend/Interview.Backend/RoomParticipants/RoomParticipantController.cs
Backend/Interview.Domain/RoomParticipants/Records/Request/RoomParticipantGetRequest.cs
Backend/Interview.Domain/RoomParticipants/Service/RoomParticipantService.cs

Нужно для того, чтоб корректно определить кого можно подключать к ws://.../code

Backend, RoomParticipantController - GetParticipant

---

Backend/Interview.Domain/Rooms/Service/Records/Response/Detail/RoomUserDetail.cs
Backend/Interview.Infrastructure/Rooms/RoomRepository.cs

Аватар у пользователей в запросе страницы комнат

Backend, RoomRepository - User avatar in GetDetailedPageAsync

---

Backend/Interview.Domain/Rooms/Service/Records/Request/RoomCreateRequest.cs
Backend/Interview.Domain/Rooms/Service/RoomService.cs

Передача expert и examinee в запросе на создание комнаты.

Backend, RoomService - Different participans in room create

---

Backend/Interview.Backend/Auth/AuthController.cs

Возможность делать redicreUri с разными параметрами. Нужно, когда фронт добавляет свои параметры для редиректа после логина

Backend, AuthController - Non absolute redirect check

---

Backend/Interview.Backend/WebSocket/Events/ConnectionListener/VideoChatConnectionListener.cs
Backend/Interview.Backend/WebSocket/Events/Handlers/JoinVideoChatWebSocketEventHandler.cs

Restricted the type of users that can connect to video chat

WebSocket - Restricted the type of users that can connect to video chat

---

Backend/Interview.Domain/Questions/Permissions/QuestionServicePermissionAccessor.cs
Backend/Interview.Domain/Users/Permissions/IPermissionRepository.cs
Backend/Interview.Domain/Users/Roles/RoleName.cs
Backend/Interview.Domain/Users/Service/UserService.cs
Backend/Interview.Infrastructure/Users/PermissionRepository.cs

Added new default permissions for user and added additional permissions that are not available to the user

Backend, UserService - Added new default permissions for user
